# ==========================================================================
# CRE WORKFLOW SETTINGS FILE
# ==========================================================================

staging-settings:
  user-workflow:
    workflow-name: "tree-workflow-staging"
  workflow-artifacts:
    workflow-path: "./main.ts"
    config-path: "./config.staging.json"
    secrets-path: ""
    

# ==========================================================================
production-settings:
  user-workflow:
    workflow-name: "tree-workflow-production"
  workflow-artifacts:
    workflow-path: "./main.ts"
    config-path: "./config.production.json"
    secrets-path: ""